spring.application.name=marketplace

spring.datasource.url=jdbc:postgresql://localhost:5432/BancoDeDadosFigurinhas
spring.datasource.username=projetoBD
spring.datasource.password=Senha123456

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

server.port=8081
